// <auto-generated />
using System;
using Gestionnaire_MDP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestionnaire_MDP.Data.Migrations
{
    [DbContext(typeof(ContexteMdp))]
    partial class ContexteMdpModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestionnaire_MDP.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntraId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Gestionnaire_MDP.Entities.Vault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Argon2HashLength")
                        .HasColumnType("int");

                    b.Property<int>("Argon2Iterations")
                        .HasColumnType("int");

                    b.Property<int>("Argon2MemoryKb")
                        .HasColumnType("int");

                    b.Property<int>("Argon2Parallelism")
                        .HasColumnType("int");

                    b.Property<byte[]>("Argon2Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Argon2Version")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashMdp")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Vaults", (string)null);
                });

            modelBuilder.Entity("Gestionnaire_MDP.Entities.VaultEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("EncryptedData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("EncryptionIv")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("EncryptionTag")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VaultId");

                    b.ToTable("VaultEntries", (string)null);
                });

            modelBuilder.Entity("Gestionnaire_MDP.Entities.Vault", b =>
                {
                    b.HasOne("Gestionnaire_MDP.Entities.User", "User")
                        .WithOne("Vault")
                        .HasForeignKey("Gestionnaire_MDP.Entities.Vault", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gestionnaire_MDP.Entities.VaultEntry", b =>
                {
                    b.HasOne("Gestionnaire_MDP.Entities.Vault", "Vault")
                        .WithMany("VaultEntries")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Gestionnaire_MDP.Entities.User", b =>
                {
                    b.Navigation("Vault")
                        .IsRequired();
                });

            modelBuilder.Entity("Gestionnaire_MDP.Entities.Vault", b =>
                {
                    b.Navigation("VaultEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
